env:
  browser: true
  node: true
  jasmine: true

extends: 'eslint:recommended'
exclude_paths:
   "src/sign-test.js"

rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: 0
