
name: oneforshaun
version: '0.0.1' # always from master
summary: Automated non-container application build (Ubuntu)
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: 'stable'
confinement: 'strict'

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
